In [ ]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score,accuracy_score
import string



In [ ]:
x="/content/drive/My Drive/Project1/sms_spam.csv"
data=pd.read_csv(x,encoding="latin-1")

In [ ]:
data.head(5)

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [ ]:
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
data.rename(columns={'v1':'Class','v2':'Text'},inplace=True)
data['numClass']=data['Class'].map({'ham':0,'spam':1})
for i in np.arange(0,len(data.Text)):
  data.loc[i,'count']=len(data.loc[i,'Text'])
print("Unique values in the class set:",data.Class.unique())
print(data.head())

Unique values in the class set: ['ham' 'spam']
  Class                                               Text  ... numClass  count
0   ham  Go until jurong point, crazy.. Available only ...  ...        0  111.0
1   ham                      Ok lar... Joking wif u oni...  ...        0   29.0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...  ...        1  155.0
3   ham  U dun say so early hor... U c already then say...  ...        0   49.0
4   ham  Nah I don't think he goes to usf, he lives aro...  ...        0   61.0

[5 rows x 7 columns]


In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(Text):
  nopunc=[char for char in Text if char not in string.punctuation]
  nopunc=''.join(nopunc)
  clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
  return clean_words

In [ ]:
data['Text'].head().apply(process_text)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: Text, dtype: object

In [ ]:
message_bow=CountVectorizer(analyzer=process_text).fit_transform(data['Text'])
print(message_bow)

  (0, 2027)	1
  (0, 7456)	1
  (0, 8809)	1
  (0, 5685)	1
  (0, 1096)	1
  (0, 5136)	1
  (0, 8231)	1
  (0, 6846)	1
  (0, 11043)	1
  (0, 7567)	1
  (0, 6131)	1
  (0, 5135)	1
  (0, 1461)	1
  (0, 6815)	1
  (0, 4574)	1
  (0, 10845)	1
  (1, 3012)	1
  (1, 7600)	1
  (1, 2407)	1
  (1, 10952)	1
  (1, 10582)	1
  (1, 8482)	1
  (2, 1909)	1
  (2, 6244)	2
  (2, 422)	1
  :	:
  (5568, 6791)	1
  (5568, 11239)	1
  (5568, 6604)	1
  (5568, 6267)	1
  (5569, 8147)	1
  (5569, 3169)	1
  (5569, 3655)	1
  (5569, 10087)	1
  (5570, 7698)	1
  (5570, 10886)	1
  (5570, 8314)	1
  (5570, 10669)	1
  (5570, 6612)	1
  (5570, 9804)	1
  (5570, 6196)	1
  (5570, 6710)	1
  (5570, 5169)	1
  (5570, 7297)	1
  (5570, 6892)	1
  (5570, 7190)	1
  (5570, 4430)	1
  (5570, 4973)	1
  (5571, 8243)	1
  (5571, 10532)	1
  (5571, 3370)	1


In [ ]:
message_bow.shape

(5572, 11304)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(message_bow,data['numClass'],test_size=0.30,random_state=None)

In [ ]:
print(x_train.shape[0])
print(x_test.shape[0])

3900
1672


In [ ]:
classifier=KNeighborsClassifier(n_neighbors=5).fit(x_train,y_train)

In [ ]:
print(classifier.predict(x_test))
print(y_test.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [ ]:
print(classifier.predict(x_test))
print(y_test.values)
pred=classifier.predict(x_test)
print('accuracy:',accuracy_score(y_test,pred))

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
accuracy: 0.8977272727272727


In [ ]:
from sklearn.metrics import classification_report,accuracy_score
pred=classifier.predict(x_train)
print(classification_report(y_train,pred))



              precision    recall  f1-score   support

           0       0.91      1.00      0.95      3383
           1       1.00      0.36      0.53       517

    accuracy                           0.92      3900
   macro avg       0.96      0.68      0.74      3900
weighted avg       0.92      0.92      0.90      3900



In [ ]:
from sklearn.metrics import classification_report,accuracy_score
pred=classifier.predict(x_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.89      1.00      0.94      1442
           1       1.00      0.26      0.41       230

    accuracy                           0.90      1672
   macro avg       0.95      0.63      0.68      1672
weighted avg       0.91      0.90      0.87      1672

